/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings.index'
import { Route as ApiPublicBookingRequestsRouteImport } from './routes/api/public/booking-requests'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers.$id'
import { Route as AuthenticatedBookingsIdRouteImport } from './routes/_authenticated/bookings.$id'

const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBookingsRoute,
  } as any)
const ApiPublicBookingRequestsRoute =
  ApiPublicBookingRequestsRouteImport.update({
    id: '/api/public/booking-requests',
    path: '/api/public/booking-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedBookingsIdRoute = AuthenticatedBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/new': typeof AuthenticatedNewRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/api/public/booking-requests': typeof ApiPublicBookingRequestsRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/new': typeof AuthenticatedNewRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/api/public/booking-requests': typeof ApiPublicBookingRequestsRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/api/public/booking-requests': typeof ApiPublicBookingRequestsRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book'
    | '/bookings'
    | '/customers'
    | '/new'
    | '/payments'
    | '/settings'
    | '/bookings/$id'
    | '/customers/$id'
    | '/api/public/booking-requests'
    | '/bookings/'
    | '/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/book'
    | '/new'
    | '/payments'
    | '/settings'
    | '/'
    | '/bookings/$id'
    | '/customers/$id'
    | '/api/public/booking-requests'
    | '/bookings'
    | '/customers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/book'
    | '/_authenticated/bookings'
    | '/_authenticated/customers'
    | '/_authenticated/new'
    | '/_authenticated/payments'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/bookings/$id'
    | '/_authenticated/customers/$id'
    | '/api/public/booking-requests'
    | '/_authenticated/bookings/'
    | '/_authenticated/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ApiPublicBookingRequestsRoute: typeof ApiPublicBookingRequestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedBookingsRoute
    }
    '/api/public/booking-requests': {
      id: '/api/public/booking-requests'
      path: '/api/public/booking-requests'
      fullPath: '/api/public/booking-requests'
      preLoaderRoute: typeof ApiPublicBookingRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/bookings/$id': {
      id: '/_authenticated/bookings/$id'
      path: '/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthenticatedBookingsIdRouteImport
      parentRoute: typeof AuthenticatedBookingsRoute
    }
  }
}

interface AuthenticatedBookingsRouteChildren {
  AuthenticatedBookingsIdRoute: typeof AuthenticatedBookingsIdRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
}

const AuthenticatedBookingsRouteChildren: AuthenticatedBookingsRouteChildren = {
  AuthenticatedBookingsIdRoute: AuthenticatedBookingsIdRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
}

const AuthenticatedBookingsRouteWithChildren =
  AuthenticatedBookingsRoute._addFileChildren(
    AuthenticatedBookingsRouteChildren,
  )

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
    AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRouteWithChildren
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRouteWithChildren,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ApiPublicBookingRequestsRoute: ApiPublicBookingRequestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
